import { Link } from 'react-router-dom';
import { EntityCard } from '../components/EntityCard';
import { useEntities } from '../hooks/useEntityData';
import { useReconstructionDashboard } from '../hooks/useReconstructionDashboard';

export function HomePage() {
  const { entities, loading } = useEntities();
  const reconstruction = useReconstructionDashboard();
  return <section className="space-y-6">
    <div className="overflow-hidden rounded-[2rem] border border-stone-800 bg-[radial-gradient(circle_at_top,rgba(199,154,69,0.22),transparent_38%),linear-gradient(135deg,#1c1917,#030712)] p-6 shadow-glow">
      <p className="text-xs font-bold uppercase tracking-[0.28em] text-sepia-400">ItsPast dashboard</p><h1 className="mt-3 text-5xl font-black leading-none">Everything has a story.</h1><p className="mt-4 text-lg text-stone-300">The GitHub index now opens as the command board: scan, map, evidence, and reconstruction queues in one place.</p>
      <div className="mt-6 grid gap-3"><Link to="/scan" className="rounded-3xl bg-sepia-400 px-5 py-4 text-center font-black tracking-[0.18em] text-stone-950">SCAN ITS PAST</Link><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><Link to="/map" className="rounded-2xl border border-stone-700 p-3 text-center text-sm">MAP</Link><Link to="/search" className="rounded-2xl border border-stone-700 p-3 text-center text-sm">SEARCH</Link><Link to="/admin/evidence" className="rounded-2xl border border-stone-700 p-3 text-center text-sm">EVIDENCE</Link><Link to="/admin/reconstruction-jobs" className="rounded-2xl border border-stone-700 p-3 text-center text-sm">JOBS</Link></div></div>
    </div>
    <section className="grid gap-3 md:grid-cols-4"><div className="rounded-3xl border border-stone-800 bg-stone-900 p-4"><span className="text-xs uppercase tracking-[0.2em] text-stone-500">Records</span><strong className="block text-3xl text-sepia-400">{loading ? '…' : entities.length}</strong></div><div className="rounded-3xl border border-stone-800 bg-stone-900 p-4"><span className="text-xs uppercase tracking-[0.2em] text-stone-500">Queued</span><strong className="block text-3xl">{reconstruction.loading ? '…' : reconstruction.summary.queued}</strong></div><div className="rounded-3xl border border-stone-800 bg-stone-900 p-4"><span className="text-xs uppercase tracking-[0.2em] text-stone-500">Blocked</span><strong className="block text-3xl text-orange-400">{reconstruction.loading ? '…' : reconstruction.summary.blocked}</strong></div><div className="rounded-3xl border border-stone-800 bg-stone-900 p-4"><span className="text-xs uppercase tracking-[0.2em] text-stone-500">Evidence avg</span><strong className="block text-3xl">{reconstruction.loading ? '…' : reconstruction.summary.averageEvidenceScore}</strong></div></section>
    <section className="grid gap-4 lg:grid-cols-[1fr_0.9fr]"><div className="space-y-3"><p className="text-xs font-bold uppercase tracking-[0.24em] text-stone-500">Places with a past</p>{loading ? <p className="rounded-2xl border border-stone-800 bg-stone-900 p-4 text-stone-400">Loading records…</p> : entities.slice(0,3).map((entity) => <EntityCard key={entity.id} entity={entity} />)}</div><div className="space-y-3"><p className="text-xs font-bold uppercase tracking-[0.24em] text-stone-500">Reconstruction lifecycle</p>{reconstruction.loading ? <p className="rounded-2xl border border-stone-800 bg-stone-900 p-4 text-stone-400">Loading jobs…</p> : reconstruction.jobs.slice(0,3).map((job) => <Link key={job.id} to={`/reconstruction/${job.entityId}`} className="block rounded-3xl border border-stone-800 bg-stone-900 p-4"><div className="flex items-center justify-between gap-3"><div><strong>{job.entityName}</strong><p className="text-sm text-stone-400">{job.targetYear} · {job.evidenceScore}/100 evidence</p></div><span className="rounded-full bg-stone-950 px-3 py-1 text-xs font-bold text-sepia-400">{job.status}</span></div></Link>)}</div></section>
  </section>;
}
