-- Deprecated placeholder evidence package.
-- Real provenance/evidence examples now ship in real_user_data.sql.
-- This file intentionally does nothing so public seeds cannot fail on placeholder IDs.
