-- Real user-facing seed data. Source-backed public records only.

insert into entity_types (slug, label, description) values
('building','Building','Physical buildings and structures'),('business','Business','Businesses tied to a place'),('bridge','Bridge','Bridge infrastructure'),('infrastructure','Infrastructure','Rail, road, utility, or civil works'),('landmark','Landmark','Recognized landmarks and monuments'),('neighborhood','Neighborhood','Historic districts and neighborhoods')
on conflict (slug) do nothing;

-- Pennsylvania Station (1910–1963)
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('2232dfb7-cff4-5c7a-90f1-7ff7738eb837', 'ARCHIVE', 'Wikidata item Q14707174 — Pennsylvania Station (1910–1963)', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q14707174', 'Q14707174', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('3f6ba1fe-dad9-5f03-8475-c287f68ac630', 'LIBRARY', 'Library of Congress search — Pennsylvania Station (1910–1963)', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Pennsylvania%20Station%20%281910%E2%80%931963%29', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('79d564e9-0098-50dc-ba09-31749ff21232', 'Pennsylvania Station (1910–1963)', 'Former New York City railroad station opened in 1910 and demolished beginning in 1963; seeded from Wikidata and public media metadata for ItsPast discovery.', (select id from entity_types where slug='infrastructure'), 40.7506, -73.9939, 'Seventh Avenue and 32nd Street, New York, NY', '1910', '1963', 'demolished', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('79d564e9-0098-50dc-ba09-31749ff21232','2232dfb7-cff4-5c7a-90f1-7ff7738eb837','wikidata_metadata'),('79d564e9-0098-50dc-ba09-31749ff21232','3f6ba1fe-dad9-5f03-8475-c287f68ac630','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('067cc887-fed3-548a-ac2d-fde2b900fb18', '79d564e9-0098-50dc-ba09-31749ff21232', '1910', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1910. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('067cc887-fed3-548a-ac2d-fde2b900fb18','2232dfb7-cff4-5c7a-90f1-7ff7738eb837','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('e98d1c88-c488-59d6-a724-9ca14f5d96ce', 'wikidata', 'Q14707174', 'Pennsylvania Station (1910–1963)', 'Former New York City railroad station opened in 1910 and demolished beginning in 1963; seeded from Wikidata and public media metadata for ItsPast discovery.', '1910', 'Seventh Avenue and 32nd Street, New York, NY', 40.7506, -73.9939, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q14707174', 'http://commons.wikimedia.org/wiki/Special:FilePath/Penn%20Station3.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q14707174", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q14707174", "source_url": "https://www.wikidata.org/wiki/Q14707174", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('fec7161c-0ec3-5710-bab1-5844881ec41b', '79d564e9-0098-50dc-ba09-31749ff21232', 'CONSTRUCTION', 'Pennsylvania Station (1910–1963) has a recorded inception/opening date of 1910 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1910', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q14707174", "source_url": "https://www.wikidata.org/wiki/Q14707174"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('1303fa0d-1aa5-5d80-b111-285e24a8bdf3', 'fec7161c-0ec3-5710-bab1-5844881ec41b', 'e98d1c88-c488-59d6-a724-9ca14f5d96ce', 'Wikidata structured metadata record Q14707174 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('a1fdf8c6-bc66-5662-9c20-b4bbf57ca730', '79d564e9-0098-50dc-ba09-31749ff21232', 'e98d1c88-c488-59d6-a724-9ca14f5d96ce', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Penn%20Station3.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Penn%20Station3.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, 'Seventh Avenue and 32nd Street, New York, NY') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('5b3df760-ac73-50a9-9f6c-214896419c40', '79d564e9-0098-50dc-ba09-31749ff21232', '1910', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('2edc2625-8f55-58f8-aba2-941e52a85857', '5b3df760-ac73-50a9-9f6c-214896419c40', '2232dfb7-cff4-5c7a-90f1-7ff7738eb837', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Brooklyn Bridge
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('57c8baaa-8999-5a84-8c30-583250b089f1', 'ARCHIVE', 'Wikidata item Q125006 — Brooklyn Bridge', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q125006', 'Q125006', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'CONFIRMED', true),
('6bd1408a-7163-51b1-b69e-3b453e93435e', 'LIBRARY', 'Library of Congress search — Brooklyn Bridge', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Brooklyn%20Bridge', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('21ebc2ad-e11a-5b98-87d9-c5e89014fcee', 'Brooklyn Bridge', 'Suspension/cable-stayed bridge crossing the East River between Manhattan and Brooklyn; seeded as a high-confidence public landmark record.', (select id from entity_types where slug='bridge'), 40.705666666, -73.996333333, 'Brooklyn Bridge, New York, NY', '1883', null, 'existing', 'CONFIRMED', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('21ebc2ad-e11a-5b98-87d9-c5e89014fcee','57c8baaa-8999-5a84-8c30-583250b089f1','wikidata_metadata'),('21ebc2ad-e11a-5b98-87d9-c5e89014fcee','6bd1408a-7163-51b1-b69e-3b453e93435e','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('5b6b29d3-1198-5d6a-9acc-0613b61e4505', '21ebc2ad-e11a-5b98-87d9-c5e89014fcee', '1883', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1883. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'CONFIRMED') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('5b6b29d3-1198-5d6a-9acc-0613b61e4505','57c8baaa-8999-5a84-8c30-583250b089f1','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('80996b4f-085a-5a8f-8339-29d72a8c0965', 'wikidata', 'Q125006', 'Brooklyn Bridge', 'Suspension/cable-stayed bridge crossing the East River between Manhattan and Brooklyn; seeded as a high-confidence public landmark record.', '1883', 'Brooklyn Bridge, New York, NY', 40.705666666, -73.996333333, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q125006', 'http://commons.wikimedia.org/wiki/Special:FilePath/Brooklyn%20Bridge%20and%20the%20Lower%20Manhattan%20skyline%20from%20Pebble%20Beach%2C%20New%20York.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q125006", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q125006", "source_url": "https://www.wikidata.org/wiki/Q125006", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "CONFIRMED"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('502cb96f-c577-5bc8-a49d-44eabb958bdf', '21ebc2ad-e11a-5b98-87d9-c5e89014fcee', 'CONSTRUCTION', 'Brooklyn Bridge has a recorded inception/opening date of 1883 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1883', 'YEAR', 'CONFIRMED', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q125006", "source_url": "https://www.wikidata.org/wiki/Q125006"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('2534a464-c6e6-55e5-ae0d-e0eeeed97f2d', '502cb96f-c577-5bc8-a49d-44eabb958bdf', '80996b4f-085a-5a8f-8339-29d72a8c0965', 'Wikidata structured metadata record Q125006 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('12e0f5f9-b934-5409-bfbe-020ee86d8177', '21ebc2ad-e11a-5b98-87d9-c5e89014fcee', '80996b4f-085a-5a8f-8339-29d72a8c0965', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Brooklyn%20Bridge%20and%20the%20Lower%20Manhattan%20skyline%20from%20Pebble%20Beach%2C%20New%20York.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Brooklyn%20Bridge%20and%20the%20Lower%20Manhattan%20skyline%20from%20Pebble%20Beach%2C%20New%20York.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, 'Brooklyn Bridge, New York, NY') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('37188cc8-c2e2-5eba-aa9d-42be5676da6d', '21ebc2ad-e11a-5b98-87d9-c5e89014fcee', '1883', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('a0d39c7d-b263-59ba-b60a-4090787b9c22', '37188cc8-c2e2-5eba-aa9d-42be5676da6d', '57c8baaa-8999-5a84-8c30-583250b089f1', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Eads Bridge
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('b2b6ce86-4fe2-51ec-9a40-e52919e3662b', 'ARCHIVE', 'Wikidata item Q1239907 — Eads Bridge', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q1239907', 'Q1239907', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('49ff101b-aa0a-52eb-835f-660a8b55102a', 'LIBRARY', 'Library of Congress search — Eads Bridge', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Eads%20Bridge', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('3d53c3ee-b2ef-551e-a35a-7a97dbf62306', 'Eads Bridge', 'Bridge spanning the Mississippi River at St. Louis, seeded from Wikidata as a real infrastructure discovery.', (select id from entity_types where slug='bridge'), 38.628056, -90.171389, 'Mississippi River at St. Louis, Missouri', '1874', null, 'existing', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('3d53c3ee-b2ef-551e-a35a-7a97dbf62306','b2b6ce86-4fe2-51ec-9a40-e52919e3662b','wikidata_metadata'),('3d53c3ee-b2ef-551e-a35a-7a97dbf62306','49ff101b-aa0a-52eb-835f-660a8b55102a','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('ed545fea-407a-518a-ba9f-e6fb6c502c78', '3d53c3ee-b2ef-551e-a35a-7a97dbf62306', '1874', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1874. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('ed545fea-407a-518a-ba9f-e6fb6c502c78','b2b6ce86-4fe2-51ec-9a40-e52919e3662b','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('b083a1af-b245-59d5-84e1-7b8311e4ebf7', 'wikidata', 'Q1239907', 'Eads Bridge', 'Bridge spanning the Mississippi River at St. Louis, seeded from Wikidata as a real infrastructure discovery.', '1874', 'Mississippi River at St. Louis, Missouri', 38.628056, -90.171389, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q1239907', 'http://commons.wikimedia.org/wiki/Special:FilePath/Eads%20Bridge%20panorama%2020090119.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q1239907", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q1239907", "source_url": "https://www.wikidata.org/wiki/Q1239907", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('df64b726-485a-5728-b06f-d925b7cc2fd5', '3d53c3ee-b2ef-551e-a35a-7a97dbf62306', 'CONSTRUCTION', 'Eads Bridge has a recorded inception/opening date of 1874 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1874', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q1239907", "source_url": "https://www.wikidata.org/wiki/Q1239907"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('36efbd2b-f6be-5a6f-ae97-20b4c87f5153', 'df64b726-485a-5728-b06f-d925b7cc2fd5', 'b083a1af-b245-59d5-84e1-7b8311e4ebf7', 'Wikidata structured metadata record Q1239907 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('c9033201-b5f9-5874-b5fc-da5665b9b59a', '3d53c3ee-b2ef-551e-a35a-7a97dbf62306', 'b083a1af-b245-59d5-84e1-7b8311e4ebf7', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Eads%20Bridge%20panorama%2020090119.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Eads%20Bridge%20panorama%2020090119.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, 'Mississippi River at St. Louis, Missouri') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('bd7190a7-6a01-5a51-9626-f3c51d5f465d', '3d53c3ee-b2ef-551e-a35a-7a97dbf62306', '1874', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('cf298dbc-4ce3-5b7b-9872-061952d0fc96', 'bd7190a7-6a01-5a51-9626-f3c51d5f465d', 'b2b6ce86-4fe2-51ec-9a40-e52919e3662b', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Pullman National Historical Park
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('abba7889-ec1d-5e86-9ff0-875b80250044', 'ARCHIVE', 'Wikidata item Q7259479 — Pullman National Historical Park', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q7259479', 'Q7259479', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('29515b28-e911-53a1-9838-12b1480005a8', 'LIBRARY', 'Library of Congress search — Pullman National Historical Park', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Pullman%20National%20Historical%20Park', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('dc409d34-3aad-564f-9205-ad847849e8a3', 'Pullman National Historical Park', 'Historic district and national historical park in Chicago associated with the Pullman company town.', (select id from entity_types where slug='neighborhood'), 41.697222, -87.609444, 'Pullman, Chicago, IL', '1880', null, 'changed', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('dc409d34-3aad-564f-9205-ad847849e8a3','abba7889-ec1d-5e86-9ff0-875b80250044','wikidata_metadata'),('dc409d34-3aad-564f-9205-ad847849e8a3','29515b28-e911-53a1-9838-12b1480005a8','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('d5184b9a-3a83-56e4-91c4-89459f2cf14b', 'dc409d34-3aad-564f-9205-ad847849e8a3', '1880', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1880. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('d5184b9a-3a83-56e4-91c4-89459f2cf14b','abba7889-ec1d-5e86-9ff0-875b80250044','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('0ad30e11-9b71-5d57-b611-32692d00b21f', 'wikidata', 'Q7259479', 'Pullman National Historical Park', 'Historic district and national historical park in Chicago associated with the Pullman company town.', '1880', 'Pullman, Chicago, IL', 41.697222, -87.609444, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q7259479', 'http://commons.wikimedia.org/wiki/Special:FilePath/Pullman%20Chicago%20Clock%20Tower.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q7259479", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q7259479", "source_url": "https://www.wikidata.org/wiki/Q7259479", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('1b8d9a7c-ce64-5994-88a4-aa1f76b97ba4', 'dc409d34-3aad-564f-9205-ad847849e8a3', 'CONSTRUCTION', 'Pullman National Historical Park has a recorded inception/opening date of 1880 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1880', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q7259479", "source_url": "https://www.wikidata.org/wiki/Q7259479"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('82c47b62-47b6-5f83-a358-f517ecaed3dd', '1b8d9a7c-ce64-5994-88a4-aa1f76b97ba4', '0ad30e11-9b71-5d57-b611-32692d00b21f', 'Wikidata structured metadata record Q7259479 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('f2a0e04d-a8d3-553f-af30-28fd8d8748b0', 'dc409d34-3aad-564f-9205-ad847849e8a3', '0ad30e11-9b71-5d57-b611-32692d00b21f', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Pullman%20Chicago%20Clock%20Tower.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Pullman%20Chicago%20Clock%20Tower.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, 'Pullman, Chicago, IL') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('c9dd931b-cab1-556f-b535-356e821ff2e7', 'dc409d34-3aad-564f-9205-ad847849e8a3', '1880', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('02443067-1b31-51f0-9024-1b34f9c6d40d', 'c9dd931b-cab1-556f-b535-356e821ff2e7', 'abba7889-ec1d-5e86-9ff0-875b80250044', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Fox Theatre (Detroit)
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('c75f719d-87f1-57d0-b93a-31321bea3ba3', 'ARCHIVE', 'Wikidata item Q3080199 — Fox Theatre (Detroit)', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q3080199', 'Q3080199', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('11e40f7c-a0b3-5a2b-98ea-662796a39895', 'LIBRARY', 'Library of Congress search — Fox Theatre (Detroit)', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Fox%20Theatre%20%28Detroit%29', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('0430982b-b1fa-5e10-ae14-6153d56a98e7', 'Fox Theatre (Detroit)', 'Theater and former movie palace in Detroit, opened in 1928; seeded with real coordinates and source provenance.', (select id from entity_types where slug='building'), 42.3386, -83.052236, '2211 Woodward Ave, Detroit, MI', '1928', null, 'renovated', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('0430982b-b1fa-5e10-ae14-6153d56a98e7','c75f719d-87f1-57d0-b93a-31321bea3ba3','wikidata_metadata'),('0430982b-b1fa-5e10-ae14-6153d56a98e7','11e40f7c-a0b3-5a2b-98ea-662796a39895','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('13c34607-6ff0-5a05-8315-d38c9587b113', '0430982b-b1fa-5e10-ae14-6153d56a98e7', '1928', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1928. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('13c34607-6ff0-5a05-8315-d38c9587b113','c75f719d-87f1-57d0-b93a-31321bea3ba3','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('9d5a0532-d3e9-5cb8-ad07-f916b6f4b287', 'wikidata', 'Q3080199', 'Fox Theatre (Detroit)', 'Theater and former movie palace in Detroit, opened in 1928; seeded with real coordinates and source provenance.', '1928', '2211 Woodward Ave, Detroit, MI', 42.3386, -83.052236, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q3080199', 'http://commons.wikimedia.org/wiki/Special:FilePath/Foxdetroitmarqueenightshot2.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q3080199", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q3080199", "source_url": "https://www.wikidata.org/wiki/Q3080199", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('3851bede-f8fa-5f0e-a716-cc8a1996e4f7', '0430982b-b1fa-5e10-ae14-6153d56a98e7', 'CONSTRUCTION', 'Fox Theatre (Detroit) has a recorded inception/opening date of 1928 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1928', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q3080199", "source_url": "https://www.wikidata.org/wiki/Q3080199"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('1f3caab1-abea-5a4a-b0f6-4338aa59e5a0', '3851bede-f8fa-5f0e-a716-cc8a1996e4f7', '9d5a0532-d3e9-5cb8-ad07-f916b6f4b287', 'Wikidata structured metadata record Q3080199 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('dcc30270-6cf5-50b8-b3ab-386b406b4f1d', '0430982b-b1fa-5e10-ae14-6153d56a98e7', '9d5a0532-d3e9-5cb8-ad07-f916b6f4b287', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Foxdetroitmarqueenightshot2.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Foxdetroitmarqueenightshot2.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '2211 Woodward Ave, Detroit, MI') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('e64d0823-eea9-5f57-bbca-da7b9da11214', '0430982b-b1fa-5e10-ae14-6153d56a98e7', '1928', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('47063f64-207b-5d09-8f37-40901178d37e', 'e64d0823-eea9-5f57-bbca-da7b9da11214', 'c75f719d-87f1-57d0-b93a-31321bea3ba3', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Los Angeles Union Station
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('f52b29c1-466e-558a-bc05-6f2d08798af4', 'ARCHIVE', 'Wikidata item Q198019 — Los Angeles Union Station', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q198019', 'Q198019', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('823992ca-c11a-5e89-8a55-b140d17fc4e9', 'LIBRARY', 'Library of Congress search — Los Angeles Union Station', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Los%20Angeles%20Union%20Station', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7', 'Los Angeles Union Station', 'Main railroad station in Los Angeles, opened in 1939; seeded as a public transportation landmark.', (select id from entity_types where slug='infrastructure'), 34.0551, -118.235, '800 N Alameda St, Los Angeles, CA', '1939', null, 'existing', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7','f52b29c1-466e-558a-bc05-6f2d08798af4','wikidata_metadata'),('b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7','823992ca-c11a-5e89-8a55-b140d17fc4e9','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('57b2d66c-cf40-5571-b701-058620e3c479', 'b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7', '1939', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1939. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('57b2d66c-cf40-5571-b701-058620e3c479','f52b29c1-466e-558a-bc05-6f2d08798af4','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('cc67e870-12a2-52b0-adbc-8cfd4936d2d7', 'wikidata', 'Q198019', 'Los Angeles Union Station', 'Main railroad station in Los Angeles, opened in 1939; seeded as a public transportation landmark.', '1939', '800 N Alameda St, Los Angeles, CA', 34.0551, -118.235, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q198019', 'http://commons.wikimedia.org/wiki/Special:FilePath/20140830%2050%20Los%20Angeles%20Union%20Station%20%2815360153108%29.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q198019", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q198019", "source_url": "https://www.wikidata.org/wiki/Q198019", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('0df7a2dc-f85c-5974-b42d-ddf1e901fe82', 'b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7', 'CONSTRUCTION', 'Los Angeles Union Station has a recorded inception/opening date of 1939 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1939', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q198019", "source_url": "https://www.wikidata.org/wiki/Q198019"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('bece8cd4-1d5f-55d4-9014-6b9d873f6914', '0df7a2dc-f85c-5974-b42d-ddf1e901fe82', 'cc67e870-12a2-52b0-adbc-8cfd4936d2d7', 'Wikidata structured metadata record Q198019 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('8cbfa0f6-3cc1-5739-80d4-97794f585ab5', 'b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7', 'cc67e870-12a2-52b0-adbc-8cfd4936d2d7', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/20140830%2050%20Los%20Angeles%20Union%20Station%20%2815360153108%29.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/20140830%2050%20Los%20Angeles%20Union%20Station%20%2815360153108%29.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '800 N Alameda St, Los Angeles, CA') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('8ef08937-4c51-559a-bf2b-015ea73a8dc1', 'b990d109-9ec5-5e4c-8542-b0ccf3ebd0d7', '1939', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('14f3d26b-5887-5ff3-9212-7cec3f78bedf', '8ef08937-4c51-559a-bf2b-015ea73a8dc1', 'f52b29c1-466e-558a-bc05-6f2d08798af4', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Detroit Public Library Main Branch
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('ed2352d5-a92e-5860-8030-1876e86befc4', 'ARCHIVE', 'Wikidata item Q131913777 — Detroit Public Library Main Branch', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q131913777', 'Q131913777', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('ec303e49-c67a-5400-8ce7-5d784eb2ceca', 'LIBRARY', 'Library of Congress search — Detroit Public Library Main Branch', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Detroit%20Public%20Library%20Main%20Branch', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('e16b8d51-f708-522c-82be-0ab41cd1d132', 'Detroit Public Library Main Branch', 'Main public library building in Detroit, opened in 1921; seeded as a real civic building record.', (select id from entity_types where slug='building'), 42.3586, -83.0667, '5201 Woodward Ave, Detroit, MI', '1921', null, 'existing', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('e16b8d51-f708-522c-82be-0ab41cd1d132','ed2352d5-a92e-5860-8030-1876e86befc4','wikidata_metadata'),('e16b8d51-f708-522c-82be-0ab41cd1d132','ec303e49-c67a-5400-8ce7-5d784eb2ceca','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('ddd1def4-7cb7-5cb3-90db-6824be614650', 'e16b8d51-f708-522c-82be-0ab41cd1d132', '1921', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1921. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('ddd1def4-7cb7-5cb3-90db-6824be614650','ed2352d5-a92e-5860-8030-1876e86befc4','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('4ee58a33-e41d-502d-aa3a-35736760d59c', 'wikidata', 'Q131913777', 'Detroit Public Library Main Branch', 'Main public library building in Detroit, opened in 1921; seeded as a real civic building record.', '1921', '5201 Woodward Ave, Detroit, MI', 42.3586, -83.0667, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q131913777', 'http://commons.wikimedia.org/wiki/Special:FilePath/Detroit%20Public%20Library%20July%202018%2002.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q131913777", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q131913777", "source_url": "https://www.wikidata.org/wiki/Q131913777", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('089ad3d2-ca18-5beb-a35e-460cf7db1825', 'e16b8d51-f708-522c-82be-0ab41cd1d132', 'CONSTRUCTION', 'Detroit Public Library Main Branch has a recorded inception/opening date of 1921 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1921', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q131913777", "source_url": "https://www.wikidata.org/wiki/Q131913777"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('8c887dbc-ef42-52d6-8afb-56ca09eaee14', '089ad3d2-ca18-5beb-a35e-460cf7db1825', '4ee58a33-e41d-502d-aa3a-35736760d59c', 'Wikidata structured metadata record Q131913777 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('34c2bc64-c996-572b-ba7a-d4e034e34c7c', 'e16b8d51-f708-522c-82be-0ab41cd1d132', '4ee58a33-e41d-502d-aa3a-35736760d59c', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Detroit%20Public%20Library%20July%202018%2002.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Detroit%20Public%20Library%20July%202018%2002.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '5201 Woodward Ave, Detroit, MI') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('ddb12c36-f84e-5e0a-b87e-1512aceb2362', 'e16b8d51-f708-522c-82be-0ab41cd1d132', '1921', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('1260e85d-0d6c-5253-a75b-2202bcd226ed', 'ddb12c36-f84e-5e0a-b87e-1512aceb2362', 'ed2352d5-a92e-5860-8030-1876e86befc4', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Old Post Office (Washington, D.C.)
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('4274cbf9-f8ec-5b2c-813f-eecbd8c45242', 'ARCHIVE', 'Wikidata item Q1141542 — Old Post Office (Washington, D.C.)', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q1141542', 'Q1141542', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('b073c32f-26d7-5907-9e94-6f6d977bcb80', 'LIBRARY', 'Library of Congress search — Old Post Office (Washington, D.C.)', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Old%20Post%20Office%20%28Washington%2C%20D.C.%29', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('88576899-379a-5ed3-9bb9-72b77aceaaaa', 'Old Post Office (Washington, D.C.)', 'Historic building on Pennsylvania Avenue in Washington, D.C.; seeded with real source references and coordinates.', (select id from entity_types where slug='building'), 38.893977777, -77.027975, '1100 Pennsylvania Ave NW, Washington, DC', '1899', null, 'renovated', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('88576899-379a-5ed3-9bb9-72b77aceaaaa','4274cbf9-f8ec-5b2c-813f-eecbd8c45242','wikidata_metadata'),('88576899-379a-5ed3-9bb9-72b77aceaaaa','b073c32f-26d7-5907-9e94-6f6d977bcb80','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('ae6640e0-e06b-52b8-9308-e5832dcd6c81', '88576899-379a-5ed3-9bb9-72b77aceaaaa', '1899', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1899. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('ae6640e0-e06b-52b8-9308-e5832dcd6c81','4274cbf9-f8ec-5b2c-813f-eecbd8c45242','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('0acf8c1d-f9a2-5db2-82a7-cfdcb6559973', 'wikidata', 'Q1141542', 'Old Post Office (Washington, D.C.)', 'Historic building on Pennsylvania Avenue in Washington, D.C.; seeded with real source references and coordinates.', '1899', '1100 Pennsylvania Ave NW, Washington, DC', 38.893977777, -77.027975, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q1141542', 'http://commons.wikimedia.org/wiki/Special:FilePath/Old%20Post%20Office%20Building%20Washington%20DC.JPG', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q1141542", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q1141542", "source_url": "https://www.wikidata.org/wiki/Q1141542", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('cd00381d-43e3-5da2-9c39-691d608fc072', '88576899-379a-5ed3-9bb9-72b77aceaaaa', 'CONSTRUCTION', 'Old Post Office (Washington, D.C.) has a recorded inception/opening date of 1899 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1899', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q1141542", "source_url": "https://www.wikidata.org/wiki/Q1141542"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('96cd6929-9ea5-58ff-8d60-71a6aaae3ed4', 'cd00381d-43e3-5da2-9c39-691d608fc072', '0acf8c1d-f9a2-5db2-82a7-cfdcb6559973', 'Wikidata structured metadata record Q1141542 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('ebd0795f-7a16-5ad1-a393-e9c6eaed0685', '88576899-379a-5ed3-9bb9-72b77aceaaaa', '0acf8c1d-f9a2-5db2-82a7-cfdcb6559973', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Old%20Post%20Office%20Building%20Washington%20DC.JPG', 'http://commons.wikimedia.org/wiki/Special:FilePath/Old%20Post%20Office%20Building%20Washington%20DC.JPG', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '1100 Pennsylvania Ave NW, Washington, DC') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('2f92c848-b95d-5783-a211-b5754722636c', '88576899-379a-5ed3-9bb9-72b77aceaaaa', '1899', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('d74be221-d206-57f3-af37-17325de520ec', '2f92c848-b95d-5783-a211-b5754722636c', '4274cbf9-f8ec-5b2c-813f-eecbd8c45242', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- SoHo Cast Iron Historic District
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('e8a42cb5-a9d9-54b8-a3b5-66b88110e667', 'ARCHIVE', 'Wikidata item Q49562891 — SoHo Cast Iron Historic District', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q49562891', 'Q49562891', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'MEDIUM', true),
('8b51c19f-f95f-5e5a-8ef6-cb7c91d05fe5', 'LIBRARY', 'Library of Congress search — SoHo Cast Iron Historic District', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=SoHo%20Cast%20Iron%20Historic%20District', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('da2fa424-915e-5ace-b970-02f0160cdc27', 'SoHo Cast Iron Historic District', 'Historic district in Manhattan known for cast-iron architecture; seeded as a real district record.', (select id from entity_types where slug='neighborhood'), 40.723055555, -74.001111111, 'SoHo, Manhattan, New York, NY', '1973', null, 'existing', 'MEDIUM', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('da2fa424-915e-5ace-b970-02f0160cdc27','e8a42cb5-a9d9-54b8-a3b5-66b88110e667','wikidata_metadata'),('da2fa424-915e-5ace-b970-02f0160cdc27','8b51c19f-f95f-5e5a-8ef6-cb7c91d05fe5','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('3534140d-555d-5f11-8f2d-5d5c25094c0b', 'da2fa424-915e-5ace-b970-02f0160cdc27', '1973', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1973. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'MEDIUM') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('3534140d-555d-5f11-8f2d-5d5c25094c0b','e8a42cb5-a9d9-54b8-a3b5-66b88110e667','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('d20e806b-7157-541c-9c33-d17519eebee2', 'wikidata', 'Q49562891', 'SoHo Cast Iron Historic District', 'Historic district in Manhattan known for cast-iron architecture; seeded as a real district record.', '1973', 'SoHo, Manhattan, New York, NY', 40.723055555, -74.001111111, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q49562891', null, 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q49562891", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q49562891", "source_url": "https://www.wikidata.org/wiki/Q49562891", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "MEDIUM"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('4652dd06-9740-503c-9751-e66f632a045e', 'da2fa424-915e-5ace-b970-02f0160cdc27', 'CONSTRUCTION', 'SoHo Cast Iron Historic District has a recorded inception/opening date of 1973 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1973', 'YEAR', 'MEDIUM', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q49562891", "source_url": "https://www.wikidata.org/wiki/Q49562891"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('d12b41f3-0ca9-5de6-8a54-e8d2024c501b', '4652dd06-9740-503c-9751-e66f632a045e', 'd20e806b-7157-541c-9c33-d17519eebee2', 'Wikidata structured metadata record Q49562891 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;

-- Market Street Railway
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('f9ec61d9-0b4e-5da7-a0c7-a7d3be0aa1ca', 'ARCHIVE', 'Wikidata item Q6770765 — Market Street Railway', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q6770765', 'Q6770765', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'MEDIUM', true),
('6efa9495-af16-5e2f-8da8-465b20bf5fc2', 'LIBRARY', 'Library of Congress search — Market Street Railway', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Market%20Street%20Railway', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('19ef2e29-f001-5742-ad05-a7c4f255bfae', 'Market Street Railway', 'San Francisco streetcar and bus operator active from 1860 to 1944; seeded as a real historical transportation entity.', (select id from entity_types where slug='infrastructure'), 37.7749, -122.4194, 'San Francisco, CA', '1860', '1944', 'changed', 'MEDIUM', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('19ef2e29-f001-5742-ad05-a7c4f255bfae','f9ec61d9-0b4e-5da7-a0c7-a7d3be0aa1ca','wikidata_metadata'),('19ef2e29-f001-5742-ad05-a7c4f255bfae','6efa9495-af16-5e2f-8da8-465b20bf5fc2','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('635ff66a-ea3d-5808-bf96-cc85d2129b18', '19ef2e29-f001-5742-ad05-a7c4f255bfae', '1860', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1860. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'MEDIUM') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('635ff66a-ea3d-5808-bf96-cc85d2129b18','f9ec61d9-0b4e-5da7-a0c7-a7d3be0aa1ca','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('9a244633-5389-5ba8-b2a4-c8612ee252f5', 'wikidata', 'Q6770765', 'Market Street Railway', 'San Francisco streetcar and bus operator active from 1860 to 1944; seeded as a real historical transportation entity.', '1860', 'San Francisco, CA', 37.7749, -122.4194, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q6770765', null, 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q6770765", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q6770765", "source_url": "https://www.wikidata.org/wiki/Q6770765", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "MEDIUM"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('ed074eaa-aedd-5644-8fb5-65978a1d8dbb', '19ef2e29-f001-5742-ad05-a7c4f255bfae', 'CONSTRUCTION', 'Market Street Railway has a recorded inception/opening date of 1860 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1860', 'YEAR', 'MEDIUM', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q6770765", "source_url": "https://www.wikidata.org/wiki/Q6770765"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('ca6f601e-d20a-509b-9ba1-3065db1900da', 'ed074eaa-aedd-5644-8fb5-65978a1d8dbb', '9a244633-5389-5ba8-b2a4-c8612ee252f5', 'Wikidata structured metadata record Q6770765 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;

-- Flatiron Building
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('4f8e72d3-8bec-528a-a813-a9b3c918a00d', 'ARCHIVE', 'Wikidata item Q220728 — Flatiron Building', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q220728', 'Q220728', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('3196d149-32a5-591a-aa78-535e6a38143f', 'LIBRARY', 'Library of Congress search — Flatiron Building', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Flatiron%20Building', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('5f153dfa-3270-570e-b09d-5456a5ab8d68', 'Flatiron Building', 'Triangular skyscraper in Manhattan completed in 1902; seeded as a real public landmark record.', (select id from entity_types where slug='building'), 40.741111, -73.989722, '175 Fifth Ave, New York, NY', '1902', null, 'existing', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('5f153dfa-3270-570e-b09d-5456a5ab8d68','4f8e72d3-8bec-528a-a813-a9b3c918a00d','wikidata_metadata'),('5f153dfa-3270-570e-b09d-5456a5ab8d68','3196d149-32a5-591a-aa78-535e6a38143f','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('5c46eb25-b5ac-5964-9b2a-95eae8546423', '5f153dfa-3270-570e-b09d-5456a5ab8d68', '1902', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1902. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('5c46eb25-b5ac-5964-9b2a-95eae8546423','4f8e72d3-8bec-528a-a813-a9b3c918a00d','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('5b334c8d-2f88-5248-9697-d0b16186ac96', 'wikidata', 'Q220728', 'Flatiron Building', 'Triangular skyscraper in Manhattan completed in 1902; seeded as a real public landmark record.', '1902', '175 Fifth Ave, New York, NY', 40.741111, -73.989722, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q220728', 'http://commons.wikimedia.org/wiki/Special:FilePath/Edificio%20Fuller%20%28Flatiron%29%20en%202010%20desde%20el%20Empire%20State%20crop%20boxin.jpg', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q220728", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q220728", "source_url": "https://www.wikidata.org/wiki/Q220728", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('1eb2ba3a-3ac3-591b-80f6-2455b0a0269d', '5f153dfa-3270-570e-b09d-5456a5ab8d68', 'CONSTRUCTION', 'Flatiron Building has a recorded inception/opening date of 1902 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1902', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q220728", "source_url": "https://www.wikidata.org/wiki/Q220728"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('750de121-6b3f-5385-850e-2a91fe06c5a2', '1eb2ba3a-3ac3-591b-80f6-2455b0a0269d', '5b334c8d-2f88-5248-9697-d0b16186ac96', 'Wikidata structured metadata record Q220728 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('2032d3a1-b9e5-552d-b54a-da0714a956d3', '5f153dfa-3270-570e-b09d-5456a5ab8d68', '5b334c8d-2f88-5248-9697-d0b16186ac96', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Edificio%20Fuller%20%28Flatiron%29%20en%202010%20desde%20el%20Empire%20State%20crop%20boxin.jpg', 'http://commons.wikimedia.org/wiki/Special:FilePath/Edificio%20Fuller%20%28Flatiron%29%20en%202010%20desde%20el%20Empire%20State%20crop%20boxin.jpg', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '175 Fifth Ave, New York, NY') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('d18284a1-254f-59fd-8f45-7813e82a239b', '5f153dfa-3270-570e-b09d-5456a5ab8d68', '1902', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('460703e6-6263-5cf8-974c-80ba847bbd35', 'd18284a1-254f-59fd-8f45-7813e82a239b', '4f8e72d3-8bec-528a-a813-a9b3c918a00d', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

-- Riverside Church
insert into historical_sources (id, source_type, title, publisher, publication_date, url, archive_reference, copyright_status, description, confidence, is_public) values
('c1a2008e-7976-51fe-9edf-f7e37fe54072', 'ARCHIVE', 'Wikidata item Q1156586 — Riverside Church', 'Wikidata', null, 'https://www.wikidata.org/wiki/Q1156586', 'Q1156586', 'CC0 metadata; item statements require source review for downstream media use', 'Structured entity metadata used for coordinates, dates, descriptions and identifiers. Wikidata is a discovery/source metadata record, not the sole final historical authority.', 'HIGH', true),
('24be6d0d-943c-5f34-a770-749ae60844a8', 'LIBRARY', 'Library of Congress search — Riverside Church', 'Library of Congress', null, 'https://www.loc.gov/search/?fo=json&q=Riverside%20Church', null, 'Mixed item-level rights; search metadata/link only until individual LOC items are reviewed', 'Official LOC no-key JSON search URL captured as a research lead. Individual results require item-level rights review before storing media.', 'MEDIUM', true)
on conflict (id) do update set title=excluded.title, url=excluded.url, description=excluded.description, copyright_status=excluded.copyright_status, confidence=excluded.confidence;
insert into physical_entities (id, name, description, entity_type, latitude, longitude, address, created_date, destroyed_date, current_status, confidence_level, is_public)
values ('fa6e2f03-a2c2-5db8-b101-d786831cc4a6', 'Riverside Church', 'Interdenominational church in Manhattan with Wikidata-recorded inception and coordinates; seeded as a real landmark.', (select id from entity_types where slug='building'), 40.81178, -73.96307, '490 Riverside Dr, New York, NY', '1927', null, 'existing', 'HIGH', true)
on conflict (id) do update set name=excluded.name, description=excluded.description, entity_type=excluded.entity_type, latitude=excluded.latitude, longitude=excluded.longitude, address=excluded.address, created_date=excluded.created_date, destroyed_date=excluded.destroyed_date, current_status=excluded.current_status, confidence_level=excluded.confidence_level, is_public=true, updated_at=now();
insert into entity_sources (entity_id, source_id, relationship_type) values ('fa6e2f03-a2c2-5db8-b101-d786831cc4a6','c1a2008e-7976-51fe-9edf-f7e37fe54072','wikidata_metadata'),('fa6e2f03-a2c2-5db8-b101-d786831cc4a6','24be6d0d-943c-5f34-a770-749ae60844a8','loc_research_lead') on conflict do nothing;
insert into historical_events (id, entity_id, date, date_precision, title, description, event_type, confidence) values ('05f52978-6731-5671-8cfd-3286bc062391', 'fa6e2f03-a2c2-5db8-b101-d786831cc4a6', '1927', 'YEAR', 'Recorded inception / opening', 'Wikidata-derived date metadata records this entity at 1927. Cross-check with archival sources before using as final reconstruction evidence.', 'inception', 'HIGH') on conflict (id) do update set date=excluded.date, description=excluded.description, confidence=excluded.confidence;
insert into event_sources (event_id, source_id, relationship_type) values ('05f52978-6731-5671-8cfd-3286bc062391','c1a2008e-7976-51fe-9edf-f7e37fe54072','supports') on conflict do nothing;
insert into source_records (id, provider_id, external_id, title, description, date, location, latitude, longitude, author, publisher, source_url, media_url, license, copyright_status, raw_metadata, license_class, attribution, provenance, can_store_metadata, can_store_media, can_use_for_ai_processing) values ('22d90ce3-4a55-5c0c-81b3-b2fae38e0aed', 'wikidata', 'Q1156586', 'Riverside Church', 'Interdenominational church in Manhattan with Wikidata-recorded inception and coordinates; seeded as a real landmark.', '1927', '490 Riverside Dr, New York, NY', 40.81178, -73.96307, null, 'Wikidata', 'https://www.wikidata.org/wiki/Q1156586', 'http://commons.wikimedia.org/wiki/Special:FilePath/Riverside%20Church%2005.JPG', 'CC0 data; linked media has per-file license and must be checked separately', 'CC0_METADATA', '{"wikidata": "Q1156586", "seed": "real-user-data"}'::jsonb, 'CC0', 'Wikidata contributors; media attribution requires individual Commons file review', '{"source_provider": "wikidata", "source_id": "Q1156586", "source_url": "https://www.wikidata.org/wiki/Q1156586", "retrieved_at": "2026-08-24", "evidence_type": "structured_metadata", "confidence": "HIGH"}'::jsonb, true, 'UNKNOWN', 'UNKNOWN') on conflict (provider_id, external_id) do update set title=excluded.title, description=excluded.description, source_url=excluded.source_url, media_url=excluded.media_url, provenance=excluded.provenance;
insert into historical_claims (id, entity_id, claim_type, claim_text, event_date, date_precision, confidence, status, provenance) values ('542dcffe-99de-5870-b01a-9a65526e316b', 'fa6e2f03-a2c2-5db8-b101-d786831cc4a6', 'CONSTRUCTION', 'Riverside Church has a recorded inception/opening date of 1927 in Wikidata metadata; treat as supported metadata pending deeper archival cross-check.', '1927', 'YEAR', 'HIGH', 'SUPPORTED', '{"source_provider": "wikidata", "source_id": "Q1156586", "source_url": "https://www.wikidata.org/wiki/Q1156586"}'::jsonb) on conflict (id) do update set claim_text=excluded.claim_text, confidence=excluded.confidence, status=excluded.status;
insert into claim_evidence (id, claim_id, source_record_id, evidence_text, evidence_type, strength) values ('66dc4eaa-edab-54eb-9547-16b933b8e15e', '542dcffe-99de-5870-b01a-9a65526e316b', '22d90ce3-4a55-5c0c-81b3-b2fae38e0aed', 'Wikidata structured metadata record Q1156586 supplies the seed date, coordinates and source identifier for this public record.', 'DIRECT', 'MODERATE') on conflict (id) do nothing;
insert into historical_media_records (id, entity_id, source_record_id, media_type, thumbnail_url, image_url, caption, creator, license, copyright_status, attribution, date, location) values ('c291c854-d952-5b40-bc59-b793846f2e20', 'fa6e2f03-a2c2-5db8-b101-d786831cc4a6', '22d90ce3-4a55-5c0c-81b3-b2fae38e0aed', 'PHOTOGRAPH', 'http://commons.wikimedia.org/wiki/Special:FilePath/Riverside%20Church%2005.JPG', 'http://commons.wikimedia.org/wiki/Special:FilePath/Riverside%20Church%2005.JPG', 'Wikimedia Commons image linked by Wikidata. Per-file license must be checked before copying or AI processing.', null, 'PER_FILE_LICENSE_REVIEW_REQUIRED', 'UNKNOWN', 'Wikimedia Commons file contributors; check file metadata before reuse', null, '490 Riverside Dr, New York, NY') on conflict (id) do update set image_url=excluded.image_url, caption=excluded.caption, license=excluded.license, copyright_status=excluded.copyright_status;
insert into reconstructions (id, entity_id, target_year, status, prompt, confidence) values ('3f95e1e6-d4c2-5364-8b69-fdd2d0db4502', 'fa6e2f03-a2c2-5db8-b101-d786831cc4a6', '1927', 'INSUFFICIENT_EVIDENCE', 'AI HISTORICAL RECONSTRUCTION candidate only. Needs source images/maps/architectural evidence beyond seed metadata before generation.', 'SPECULATIVE') on conflict (id) do update set status=excluded.status, prompt=excluded.prompt, confidence=excluded.confidence;
insert into reconstruction_evidence (id, reconstruction_id, source_id, label, description) values ('61c2cbcd-6e42-5a35-af9d-7a78adfa5700', '3f95e1e6-d4c2-5364-8b69-fdd2d0db4502', 'c1a2008e-7976-51fe-9edf-f7e37fe54072', 'DOCUMENTED', 'Seed metadata documents identity, coordinates and a research date clue. It is not yet sufficient architectural evidence for generation.') on conflict do nothing;

