import { Link } from 'react-router-dom';
import { useReconstructionDashboard } from '../../src/hooks/useReconstructionDashboard';

const statusClass = (status: string) => status === 'QUEUED' ? 'bg-sepia-400 text-stone-950' : status === 'COMPLETED' ? 'bg-emerald-400 text-stone-950' : status === 'BLOCKED' ? 'bg-orange-400 text-stone-950' : status === 'RUNNING' ? 'bg-blue-400 text-stone-950' : 'bg-red-400 text-stone-950';

export function ReconstructionJobsPage() {
  const { jobs, summary, loading } = useReconstructionDashboard();
  return <section className="space-y-5"><div className="rounded-3xl border border-stone-800 bg-stone-900 p-5"><p className="text-xs font-bold uppercase tracking-[0.24em] text-sepia-400">Generation lifecycle</p><h1 className="mt-2 text-3xl font-black">Reconstruction jobs</h1><p className="mt-2 text-stone-300">Queue, blocked, running, and completed output states stay bound to the evidence gate.</p><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-6"><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Total</span><strong className="block text-2xl">{summary.total}</strong></div><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Queued</span><strong className="block text-2xl text-sepia-400">{summary.queued}</strong></div><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Running</span><strong className="block text-2xl">{summary.running}</strong></div><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Done</span><strong className="block text-2xl text-emerald-400">{summary.completed}</strong></div><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Blocked</span><strong className="block text-2xl text-orange-400">{summary.blocked}</strong></div><div className="rounded-2xl bg-stone-950 p-3"><span className="text-stone-500">Avg evidence</span><strong className="block text-2xl">{summary.averageEvidenceScore}</strong></div></div></div>{loading ? <p className="rounded-2xl border border-stone-800 bg-stone-900 p-4 text-stone-400">Reading reconstruction jobs…</p> : <div className="space-y-3">{jobs.map((job) => <article key={job.id} className="rounded-3xl border border-stone-800 bg-stone-900 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{job.entityName}</h2><p className="text-sm text-stone-400">{job.targetYear} · evidence {job.evidenceScore}/100</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${statusClass(job.status)}`}>{job.status}</span></div>{job.blockedReason ? <p className="mt-3 rounded-2xl bg-orange-950/40 p-3 text-sm text-orange-200">{job.blockedReason}</p> : <p className="mt-3 text-sm text-stone-400">Ready for generation. Output artifact attaches only after completion.</p>}<div className="mt-3 flex flex-wrap gap-2"><Link to={`/reconstruction/${job.entityId}`} className="rounded-full bg-sepia-400 px-3 py-1 text-sm font-bold text-stone-950">Open viewer</Link><Link to={`/entity/${job.entityId}`} className="rounded-full border border-stone-700 px-3 py-1 text-sm font-bold">Entity</Link></div></article>)}</div>}</section>;
}
