create extension if not exists "pgcrypto";

create type confidence_level as enum ('CONFIRMED','HIGH','MEDIUM','LOW','SPECULATIVE');
create type date_precision as enum ('EXACT','YEAR','DECADE','APPROXIMATE','UNKNOWN');
create type source_type as enum ('ARCHIVE','GOVERNMENT','NEWSPAPER','MUSEUM','LIBRARY','HISTORICAL_SOCIETY','BOOK','ACADEMIC','PHOTOGRAPH','MAP','USER_SUBMISSION','EXPERT_SUBMISSION');
create type entity_status as enum ('existing','demolished','renovated','replaced','changed','unknown');
create type reconstruction_status as enum ('PENDING','RESEARCHING','READY','FAILED','INSUFFICIENT_EVIDENCE');

create table profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, role text not null default 'user' check (role in ('user','expert','admin')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table entity_types (id uuid primary key default gen_random_uuid(), slug text unique not null, label text not null, description text);
create table locations (id uuid primary key default gen_random_uuid(), latitude double precision not null, longitude double precision not null, address text, city text, region text, country text, geohash text, created_at timestamptz not null default now());
create table physical_entities (id uuid primary key default gen_random_uuid(), name text not null, entity_type uuid references entity_types(id), description text, location_id uuid references locations(id), latitude double precision, longitude double precision, address text, created_date text, destroyed_date text, current_status entity_status not null default 'unknown', confidence_level confidence_level not null default 'LOW', is_public boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table historical_events (id uuid primary key default gen_random_uuid(), entity_id uuid references physical_entities(id) on delete cascade, date text, date_precision date_precision not null default 'UNKNOWN', title text not null, description text, event_type text, confidence confidence_level not null default 'LOW', created_at timestamptz not null default now());
create table timeline_events (id uuid primary key default gen_random_uuid(), entity_id uuid references physical_entities(id) on delete cascade, historical_event_id uuid references historical_events(id) on delete cascade, sort_order int not null default 0, created_at timestamptz not null default now());
create table historical_sources (id uuid primary key default gen_random_uuid(), source_type source_type not null, title text not null, publisher text, author text, publication_date text, url text, archive_reference text, copyright_status text, description text, confidence confidence_level not null default 'LOW', is_public boolean not null default true, created_at timestamptz not null default now());
create table historical_images (id uuid primary key default gen_random_uuid(), entity_id uuid references physical_entities(id) on delete cascade, source_id uuid references historical_sources(id), storage_path text, photographer text, image_date text, location_description text, copyright_status text, license text, description text, is_public boolean not null default true, created_at timestamptz not null default now());
create table historical_documents (id uuid primary key default gen_random_uuid(), entity_id uuid references physical_entities(id) on delete cascade, source_id uuid references historical_sources(id), storage_path text, title text not null, document_date text, description text, is_public boolean not null default true, created_at timestamptz not null default now());
create table entity_relationships (id uuid primary key default gen_random_uuid(), from_entity_id uuid references physical_entities(id) on delete cascade, to_entity_id uuid references physical_entities(id) on delete cascade, relationship_type text not null, confidence confidence_level not null default 'LOW', source_id uuid references historical_sources(id), created_at timestamptz not null default now());
create table reconstructions (id uuid primary key default gen_random_uuid(), entity_id uuid references physical_entities(id) on delete cascade, requested_by uuid references profiles(id), target_year text not null, status reconstruction_status not null default 'PENDING', prompt text, output_storage_path text, confidence confidence_level not null default 'SPECULATIVE', ai_generated boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table reconstruction_evidence (id uuid primary key default gen_random_uuid(), reconstruction_id uuid references reconstructions(id) on delete cascade, source_id uuid references historical_sources(id), label text not null check (label in ('DOCUMENTED','STRONGLY_INFERRED','ESTIMATED','AI_INTERPRETATION')), description text not null, created_at timestamptz not null default now());
create table user_contributions (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id), entity_id uuid references physical_entities(id), contribution_type text not null, title text, body text, storage_path text, visibility text not null default 'private' check (visibility in ('private','public_after_review')), status text not null default 'pending' check (status in ('pending','approved','rejected','needs_more_info')), created_at timestamptz not null default now());
create table verification_records (id uuid primary key default gen_random_uuid(), contribution_id uuid references user_contributions(id) on delete cascade, reviewer_id uuid references profiles(id), status text not null, notes text, created_at timestamptz not null default now());
create table saved_discoveries (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id) on delete cascade, entity_id uuid references physical_entities(id) on delete cascade, private boolean not null default true, created_at timestamptz not null default now(), unique(user_id, entity_id));
create table collections (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id) on delete cascade, name text not null, description text, private boolean not null default true, created_at timestamptz not null default now());
create table business_accounts (id uuid primary key default gen_random_uuid(), owner_id uuid references profiles(id), name text not null, account_type text not null default 'business', created_at timestamptz not null default now());
create table subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id), stripe_customer_id text, stripe_subscription_id text, plan text not null default 'free', status text not null default 'inactive', created_at timestamptz not null default now());
create table reconstruction_credits (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id), balance int not null default 0, updated_at timestamptz not null default now());
create table audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references profiles(id), action text not null, entity text, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index physical_entities_location_idx on physical_entities(latitude, longitude);
create index physical_entities_type_idx on physical_entities(entity_type);
create index physical_entities_status_idx on physical_entities(current_status);
create index historical_events_entity_date_idx on historical_events(entity_id, date);
create index historical_sources_type_idx on historical_sources(source_type);
create index entity_relationships_from_idx on entity_relationships(from_entity_id);
create index entity_relationships_to_idx on entity_relationships(to_entity_id);
create index saved_discoveries_user_idx on saved_discoveries(user_id);

alter table profiles enable row level security;
alter table physical_entities enable row level security;
alter table historical_events enable row level security;
alter table timeline_events enable row level security;
alter table historical_sources enable row level security;
alter table historical_images enable row level security;
alter table historical_documents enable row level security;
alter table entity_relationships enable row level security;
alter table reconstructions enable row level security;
alter table reconstruction_evidence enable row level security;
alter table user_contributions enable row level security;
alter table verification_records enable row level security;
alter table saved_discoveries enable row level security;
alter table collections enable row level security;
alter table business_accounts enable row level security;
alter table subscriptions enable row level security;
alter table reconstruction_credits enable row level security;
alter table audit_logs enable row level security;

create policy "public entities are readable" on physical_entities for select using (is_public = true);
create policy "public historical events are readable" on historical_events for select using (exists (select 1 from physical_entities pe where pe.id = entity_id and pe.is_public));
create policy "public sources are readable" on historical_sources for select using (is_public = true);
create policy "public images are readable" on historical_images for select using (is_public = true);
create policy "public documents are readable" on historical_documents for select using (is_public = true);
create policy "relationships are readable for public entities" on entity_relationships for select using (true);
create policy "users manage own profile" on profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "users create own contributions" on user_contributions for insert with check (auth.uid() = user_id);
create policy "users read own contributions" on user_contributions for select using (auth.uid() = user_id);
create policy "users manage own saved discoveries" on saved_discoveries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own collections" on collections for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users read own subscriptions" on subscriptions for select using (auth.uid() = user_id);
create policy "users read own credits" on reconstruction_credits for select using (auth.uid() = user_id);
